hightlighter: pygments
markdown: kramdown
permalink: /blog/:title/

name: Guilherme Berger
description: Guilherme Berger's personal site and blog
url: http://gberger.me

kramdown:
  enable_coderay: true

gems:
  - jekyll-redirect-from